# Generated by Django 5.2.7 on 2025-10-14 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("externalId", models.CharField(max_length=100, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("zipcode", models.IntegerField()),
                ("latitude", models.CharField(blank=True, max_length=40, null=True)),
                ("longitude", models.CharField(blank=True, max_length=40, null=True)),
                ("caption", models.TextField(blank=True, null=True)),
                ("imageURL", models.URLField()),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("username", models.CharField(max_length=60, unique=True)),
                ("passwordHash", models.CharField(max_length=255)),
                ("zipCode", models.IntegerField()),
                ("latitude", models.CharField(blank=True, max_length=40, null=True)),
                ("longitude", models.CharField(blank=True, max_length=40, null=True)),
                ("imageURL", models.URLField(blank=True, null=True)),
                ("favorites", models.JSONField(blank=True, default=list)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
